name: CI/CD Deploy to EC2 via ECR

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_FE_REPO: 468674691378.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fullstack-app
  ECR_BE_REPO: 468674691378.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fullstack-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # ===== FRONTEND =====
    - name: Log in to ECR (FE)
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_FE_REPO

    - name: Build and push FE Docker image
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest $ECR_FE_REPO:frontend-latest
        docker push $ECR_FE_REPO:frontend-latest

    # - name: Deploy to EC2 (FE)
    #   run: |
    #     echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ec2_key.pem
    #     chmod 400 ec2_key.pem
    #     ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FE_HOST }} << 'EOF'
    #       aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_FE_REPO }}
    #       docker pull ${{ env.ECR_FE_REPO }}:frontend-latest
    #       docker stop fe_app || true && docker rm fe_app || true
    #       docker run -d --name fe_app -p 80:3000 ${{ env.ECR_FE_REPO }}:frontend-latest
    #     EOF

    # ===== BACKEND =====
    - name: Log in to ECR (BE)
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BE_REPO

    - name: Build and push BE Docker image
      run: |
        docker build -t backend ./backend
        docker tag backend:latest $ECR_BE_REPO:backend-latest
        docker push $ECR_BE_REPO:backend-latest

    # - name: Deploy to EC2 (BE)
    #   run: |
    #     echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ec2_key.pem
    #     chmod 400 ec2_key.pem
    #     ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_BE_HOST }} << 'EOF'
    #       aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_BE_REPO }}
    #       docker pull ${{ env.ECR_BE_REPO }}:backend-latest
    #       docker stop be_app || true && docker rm be_app || true
    #       docker run -d --name be_app -p 3000:3000 ${{ env.ECR_BE_REPO }}:backend-latest
    #     EOF
